name: Build and test
on: push
jobs:
  build:
    runs-on: 
      - ubuntu-latest
      - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up OpenJDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "temurin"
      - name: Test
        env:
          AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
          AZURE_CONTAINER: ${{secrets.AZURE_CONTAINER}}
          AZURE_CONTAINER_DIRECTORY: ${{secrets.AZURE_CONTAINER_DIRECTORY}}
          AZURE_ACCOUNT_KEY: ${{secrets.AZURE_ACCOUNT_KEY}}
        run: ./gradlew --stacktrace test
